# general configuration
url: http://maxwellfarrior.com
baseurl: ''

resume_location_no_extension: assets/Maxwell Farrior Resume [16.05.15]

# compass configuration
config:

  # an avatar or logo (optional)
  logo: "/images/picture-of-max.jpg"
  
  # author will appear under the avatar (optional)
  author: "Maxwell Farrior"
  
  # tagline will appear under the title (optional)
  tagline: "A site dedicated to the feats and works of Maxwell Farrior"
  #  tagline: "A collection of works and feats"
  
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Output to testing.maxwellfarrior.com
destination: /srv/www/testing.maxwellfarrior.com

